# 🏷️ **Etude de marché "Nettoyage"**

##  **Import des librairies**

In [1]:
import numpy as np
import pandas as pd
import pycountry
import glob
import os
import country_converter as coco
from functools import reduce

In [2]:

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

# Afficher toutes les lignes (si besoin)
pd.set_option('display.max_rows', None)

# Empêcher l'affichage tronqué
pd.set_option('display.max_colwidth', None)

In [3]:
csv_files = glob.glob("../data_raw/*.csv")
print(csv_files)

['../data_raw\\API_LP.LPI.OVRL.XQ_DS2_en_csv_v2_6417.csv', '../data_raw\\API_NE.CON.PRVT.PC.KD_DS2_en_csv_v2_6439.csv', '../data_raw\\API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_129964.csv', '../data_raw\\API_PV.EST_DS2_en_csv_v2_126909.csv', '../data_raw\\API_SP.POP.TOTL_DS2_en_csv_v2_130083.csv', '../data_raw\\API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_129596.csv', '../data_raw\\API_TM.TAX.MRCH.SM.AR.ZS_DS2_en_csv_v2_126349.csv', '../data_raw\\DisponibiliteAlimentaire_2017.csv', '../data_raw\\dispo_alimentaire.csv', '../data_raw\\food_balances_poultry.csv', '../data_raw\\livestock_production.csv', '../data_raw\\per-capita-nitrous-oxide-agriculture.csv', '../data_raw\\Population_2000_2018.csv', '../data_raw\\prices.csv', '../data_raw\\share-of-arable-land-which-is-organic.csv', '../data_raw\\sql-pays.csv', '../data_raw\\trade.csv']

##  **Nettoyage des fichiers**

##  Indice de performance Logistique

In [4]:
logistique = pd.read_csv("../data_raw/API_LP.LPI.OVRL.XQ_DS2_en_csv_v2_6417.csv", skiprows=4)
logistique.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Logistics performance index: Overall (1=low to 5=high),LP.LPI.OVRL.XQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Logistics performance index: Overall (1=low to 5=high),LP.LPI.OVRL.XQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.385238,NaN,NaN,2.380000,NaN,2.464211,NaN,2.469728,NaN,2.578623,NaN,2.492222,NaN,NaN,NaN,2.618182,NaN,NaN,NaN
2,Afghanistan,AFG,Logistics performance index: Overall (1=low to 5=high),LP.LPI.OVRL.XQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.210000,NaN,NaN,2.240000,NaN,2.300000,NaN,2.069573,NaN,2.141282,NaN,1.950000,NaN,NaN,NaN,1.900000,NaN,NaN,NaN
3,Africa Western and Central,AFW,Logistics performance index: Overall (1=low to 5=high),LP.LPI.OVRL.XQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.303333,NaN,NaN,2.463889,NaN,2.448333,NaN,2.451831,NaN,2.349977,NaN,2.413333,NaN,NaN,NaN,2.473333,NaN,NaN,NaN
4,Angola,AGO,Logistics performance index: Overall (1=low to 5=high),LP.LPI.OVRL.XQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.480000,NaN,NaN,2.250000,NaN,2.280000,NaN,2.542980,NaN,2.241183,NaN,2.050000,NaN,NaN,NaN,2.100000,NaN,NaN,NaN

In [5]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in logistique.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
logistique = logistique[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
logistique = logistique.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {logistique.shape}")
logistique.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.385238,NaN,NaN,2.380000,NaN,2.464211,NaN,2.469728,NaN,2.578623,NaN,2.492222,NaN,NaN,NaN,2.618182,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.210000,NaN,NaN,2.240000,NaN,2.300000,NaN,2.069573,NaN,2.141282,NaN,1.950000,NaN,NaN,NaN,1.900000,NaN
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.303333,NaN,NaN,2.463889,NaN,2.448333,NaN,2.451831,NaN,2.349977,NaN,2.413333,NaN,NaN,NaN,2.473333,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.480000,NaN,NaN,2.250000,NaN,2.280000,NaN,2.542980,NaN,2.241183,NaN,2.050000,NaN,NaN,NaN,2.100000,NaN

##  PIB par habitant

In [6]:
pib=pd.read_csv("../data_raw\API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_129964.csv",skiprows=4)
pib.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21732.858315,23099.940085,23889.045018,24575.660660,25791.043179,26254.742804,26004.495628,27240.802789,27412.755193,27765.653258,30245.706974,31920.239073,31888.508737,32507.084315,35059.273098,35098.797669,35937.594656,37768.566014,38904.999248,34339.939156,33729.511911,35324.072064,34095.647171,35901.653313,35657.287197,35972.866445,36117.508211,37524.928478,39287.019517,39110.276190,28976.463550,35696.309372,41649.450792,44967.344513,NaN,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1805.536162,1818.349244,1776.252463,1766.441848,1788.612381,1858.877388,1945.293715,2012.192323,2019.906634,2052.553959,2116.708226,2187.101894,2249.467104,2308.467503,2439.229394,2602.321141,2786.101474,2972.278139,3082.393725,3041.848305,3149.290769,3253.882304,3171.731146,3291.011573,3426.709344,3456.491245,3551.146279,3703.977710,3648.261332,3742.921371,3629.566978,3907.249127,4229.086486,4352.490897,4481.246847,NaN
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813.550256,747.688045,926.507941,966.962032,971.633503,1076.087353,1121.834471,1286.949843,1333.747267,1570.698145,1765.538028,1744.060623,1988.429304,2133.241271,2224.490748,2284.075848,2213.181441,2335.795862,2432.276701,2583.485332,2561.981761,2144.166570,2122.995815,2201.722907,NaN,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1741.375500,1775.369787,1806.611963,1778.752723,1768.241377,1793.032065,1859.945239,1923.918180,1963.029201,1969.702996,2032.277961,2126.379549,2297.546727,2404.852788,2592.613321,2752.366732,2904.176505,3056.178550,3218.913431,3335.301047,3510.774499,3659.213699,3777.576842,3933.084083,4134.630237,4090.728121,4032.306271,4100.154941,4238.954649,4494.591601,4484.064642,4746.752785,5169.145547,5408.013246,5639.830732,NaN
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3340.598482,3372.596968,3143.440610,2369.241832,2374.020821,2695.805985,3013.332813,3178.494803,3254.244475,3262.975529,3326.779914,3427.853950,3824.284804,3878.507955,4262.906013,4876.287684,5404.383830,6095.999267,6651.377741,6498.169282,6607.022197,6711.390257,7354.942966,7561.039205,7990.274457,7119.726443,6843.735897,6992.728834,7347.799936,7528.382418,6450.749946,7408.126591,7924.888806,8046.817299,8347.952791,NaN

In [7]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in pib.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
pib = pib[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
pib = pib.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {pib.shape}")
pib.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,30245.706974,31920.239073,31888.508737,32507.084315,35059.273098,35098.797669,35937.594656,37768.566014,38904.999248,34339.939156,33729.511911,35324.072064,34095.647171,35901.653313,35657.287197,35972.866445,36117.508211,37524.928478,39287.019517,39110.276190,28976.463550,35696.309372,41649.450792,44967.344513
1,Africa Eastern and Southern,AFE,2116.708226,2187.101894,2249.467104,2308.467503,2439.229394,2602.321141,2786.101474,2972.278139,3082.393725,3041.848305,3149.290769,3253.882304,3171.731146,3291.011573,3426.709344,3456.491245,3551.146279,3703.977710,3648.261332,3742.921371,3629.566978,3907.249127,4229.086486,4352.490897
2,Afghanistan,AFG,813.550256,747.688045,926.507941,966.962032,971.633503,1076.087353,1121.834471,1286.949843,1333.747267,1570.698145,1765.538028,1744.060623,1988.429304,2133.241271,2224.490748,2284.075848,2213.181441,2335.795862,2432.276701,2583.485332,2561.981761,2144.166570,2122.995815,2201.722907
3,Africa Western and Central,AFW,2032.277961,2126.379549,2297.546727,2404.852788,2592.613321,2752.366732,2904.176505,3056.178550,3218.913431,3335.301047,3510.774499,3659.213699,3777.576842,3933.084083,4134.630237,4090.728121,4032.306271,4100.154941,4238.954649,4494.591601,4484.064642,4746.752785,5169.145547,5408.013246
4,Angola,AGO,3326.779914,3427.853950,3824.284804,3878.507955,4262.906013,4876.287684,5404.383830,6095.999267,6651.377741,6498.169282,6607.022197,6711.390257,7354.942966,7561.039205,7990.274457,7119.726443,6843.735897,6992.728834,7347.799936,7528.382418,6450.749946,7408.126591,7924.888806,8046.817299

##  Indice de stabilité politique

In [8]:
stabilite=pd.read_csv("../data_raw\API_PV.EST_DS2_en_csv_v2_126909.csv",skiprows=4)
stabilite.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Political Stability and Absence of Violence/Terrorism: Estimate,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.993218,1.376416,1.303461,1.286569,1.316396,1.121554,1.100847,1.285738,1.263882,1.312226,1.164568,1.210240,1.260759,1.313846,1.337510,1.335807,1.371591,1.431727,1.483080,1.432525,NaN,NaN
1,Africa Eastern and Southern,AFE,Political Stability and Absence of Violence/Terrorism: Estimate,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Political Stability and Absence of Violence/Terrorism: Estimate,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.417310,NaN,-2.427355,NaN,-2.438969,NaN,-2.035034,-2.198372,-2.295682,-2.067510,-2.219135,-2.413373,-2.691361,-2.711421,-2.579152,-2.502060,-2.418561,-2.519349,-2.411068,-2.562625,-2.662156,-2.794976,-2.753441,-2.652540,-2.702721,-2.518676,-2.544956,-2.484081,NaN,NaN
3,Africa Western and Central,AFW,Political Stability and Absence of Violence/Terrorism: Estimate,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Political Stability and Absence of Violence/Terrorism: Estimate,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.061917,NaN,-2.318058,NaN,-2.038174,NaN,-1.576180,-1.007386,-1.063121,-0.885178,-0.539453,-0.666659,-0.361787,-0.347592,-0.226182,-0.369238,-0.389323,-0.391233,-0.333232,-0.505386,-0.321580,-0.387895,-0.347209,-0.368412,-0.599918,-0.710481,-0.630109,-0.341505,NaN,NaN

In [9]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in stabilite.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
stabilite = stabilite[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
stabilite = stabilite.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {stabilite.shape}")
stabilite.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,NaN,NaN,NaN,NaN,0.993218,1.376416,1.303461,1.286569,1.316396,1.121554,1.100847,1.285738,1.263882,1.312226,1.164568,1.210240,1.260759,1.313846,1.337510,1.335807,1.371591,1.431727,1.483080,1.432525
1,Africa Eastern and Southern,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,-2.438969,NaN,-2.035034,-2.198372,-2.295682,-2.067510,-2.219135,-2.413373,-2.691361,-2.711421,-2.579152,-2.502060,-2.418561,-2.519349,-2.411068,-2.562625,-2.662156,-2.794976,-2.753441,-2.652540,-2.702721,-2.518676,-2.544956,-2.484081
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,-2.038174,NaN,-1.576180,-1.007386,-1.063121,-0.885178,-0.539453,-0.666659,-0.361787,-0.347592,-0.226182,-0.369238,-0.389323,-0.391233,-0.333232,-0.505386,-0.321580,-0.387895,-0.347209,-0.368412,-0.599918,-0.710481,-0.630109,-0.341505

##  Population Totale

In [10]:
pop=pd.read_csv("../data_raw\API_SP.POP.TOTL_DS2_en_csv_v2_130083.csv",skiprows=4)
pop.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,59069.0,59052.0,58950.0,58781.0,58047.0,58299.0,58349.0,58295.0,58368.0,58580.0,58776.0,59191.0,59909.0,60563.0,61276.0,62228.0,62901.0,61728.0,59931.0,59159.0,59331.0,60443.0,62753.0,65896.0,69005.0,73685.0,77595.0,79805.0,83021.0,86301.0,88451.0,89659.0,90588.0,91439.0,92074.0,93128.0,95138.0,97635.0,99405.0,100150.0,100917.0,101604.0,101838.0,102591.0,104110.0,105675.0,106807.0,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107624.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,153281203.0,157704381.0,162329396.0,167088245.0,171984985.0,177022314.0,182126556.0,187524135.0,193186642.0,198914573.0,204802976.0,210680842.0,217074286.0,223974122.0,230792729.0,238043099.0,245822010.0,253644643.0,261458202.0,269450407.0,277621771.0,286067346.0,294498625.0,302939121.0,311748681.0,320442961.0,329082707.0,338324002.0,347441809.0,356580375.0,366138524.0,375646235.0,385505757.0,395750933.0,406156661.0,416807868.0,427820358.0,439173286.0,450928044.0,463076637.0,475606210.0,488580707.0,502070763.0,516003448.0,530308387.0,544737983.0,559609961.0,575202699.0,590968990.0,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750503764.0,769294618.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,10756922.0,11017409.0,11290128.0,11567667.0,11853696.0,12157999.0,12469127.0,12773954.0,13059851.0,13340756.0,13611441.0,13655567.0,13169311.0,11937581.0,10991378.0,10917982.0,11190221.0,11426852.0,11420074.0,11387818.0,11523298.0,11874088.0,12045660.0,12238879.0,13278974.0,14943172.0,16250794.0,17065836.0,17763266.0,18452091.0,19159996.0,19887785.0,20130327.0,20284307.0,21378117.0,22733049.0,23560654.0,24404567.0,25424094.0,25909852.0,26482622.0,27466101.0,28284089.0,29347708.0,30560034.0,31622704.0,32792523.0,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,111246953.0,113795019.0,116444636.0,119203521.0,122086536.0,125072948.0,128176494.0,131449942.0,134911581.0,138569918.0,142337272.0,146258576.0,150402616.0,154721711.0,159166518.0,163762473.0,168585118.0,173255157.0,177880746.0,182811038.0,187889141.0,193104347.0,198485027.0,204062274.0,209566031.0,215178709.0,221191375.0,227246778.0,233360104.0,239801875.0,246415446.0,253207584.0,260297834.0,267506298.0,274968446.0,282780717.0,290841795.0,299142845.0,307725100.0,316588476.0,325663158.0,334984176.0,344586109.0,354343844.0,364358270.0,374790143.0,385360349.0,396030207.0,406992047.0,418127845.0,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,5702699.0,5763685.0,5852788.0,5991102.0,6174262.0,6388528.0,6613367.0,6842947.0,7074664.0,7317829.0,7576734.0,7847207.0,8133872.0,8435607.0,8751648.0,9082983.0,9425917.0,9779120.0,10139450.0,10497858.0,10861291.0,11238562.0,11626360.0,12023529.0,12423712.0,12827135.0,13249764.0,13699778.0,14170973.0,14660413.0,15159370.0,15667235.0,16194869.0,16747208.0,17327699.0,17943712.0,18600423.0,19291161.0,20015279.0,20778561.0,21578655.0,22414773.0,23294825.0,24218352.0,25177394.0,26165620.0,27160769.0,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

In [11]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in pop.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
pop = pop[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
pop = pop.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {pop.shape}")
pop.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,90588.0,91439.0,92074.0,93128.0,95138.0,97635.0,99405.0,100150.0,100917.0,101604.0,101838.0,102591.0,104110.0,105675.0,106807.0,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0
1,Africa Eastern and Southern,AFE,406156661.0,416807868.0,427820358.0,439173286.0,450928044.0,463076637.0,475606210.0,488580707.0,502070763.0,516003448.0,530308387.0,544737983.0,559609961.0,575202699.0,590968990.0,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750503764.0
2,Afghanistan,AFG,20130327.0,20284307.0,21378117.0,22733049.0,23560654.0,24404567.0,25424094.0,25909852.0,26482622.0,27466101.0,28284089.0,29347708.0,30560034.0,31622704.0,32792523.0,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0
3,Africa Western and Central,AFW,274968446.0,282780717.0,290841795.0,299142845.0,307725100.0,316588476.0,325663158.0,334984176.0,344586109.0,354343844.0,364358270.0,374790143.0,385360349.0,396030207.0,406992047.0,418127845.0,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0
4,Angola,AGO,16194869.0,16747208.0,17327699.0,17943712.0,18600423.0,19291161.0,20015279.0,20778561.0,21578655.0,22414773.0,23294825.0,24218352.0,25177394.0,26165620.0,27160769.0,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0

##  Taux d'urbanisation

In [12]:
urban=pd.read_csv("../data_raw\API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_129596.csv",skiprows=4)
urban.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,50.776000,50.761000,50.746000,50.730000,50.715000,50.700000,50.685000,50.670000,50.654000,50.639000,50.624000,50.609000,50.593000,50.578000,50.563000,50.548000,50.532000,50.517000,50.502000,50.487000,50.472000,50.456000,50.441000,50.426000,50.411000,50.395000,50.380000,50.365000,50.350000,50.335000,50.319000,50.304000,49.998000,49.588000,49.177000,48.767000,48.356000,47.946000,47.536000,47.127000,46.717000,46.339000,45.972000,45.606000,45.240000,44.875000,44.511000,44.147000,43.783000,43.421000,43.059000,42.940000,42.957000,42.990000,43.041000,43.108000,43.192000,43.293000,43.411000,43.546000,43.697000,43.866000,44.052000,44.254000,44.474000,NaN
1,Africa Eastern and Southern,AFE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,14.577252,14.825175,15.083802,15.363045,15.655383,15.955912,16.269384,16.588657,16.914649,17.251317,17.570661,17.895200,18.241390,18.583739,18.898834,19.219193,19.540022,19.874575,20.227304,20.565956,20.900490,21.219628,21.531318,21.903454,22.333345,22.800578,23.303936,23.805339,24.306725,24.800606,25.308714,25.742566,26.166294,26.607294,27.037575,27.408218,27.685697,27.958083,28.245921,28.532893,28.813361,29.110011,29.423890,29.734870,30.048040,30.380995,30.704020,30.958245,31.362783,31.774237,32.195595,32.628069,33.052742,33.496557,33.959633,34.447281,34.919544,35.396289,35.893398,36.384272,36.884034,37.393633,37.909012,38.424898,38.949114,NaN
2,Afghanistan,AFG,Urban population (% of total population),SP.URB.TOTL.IN.ZS,8.401000,8.684000,8.976000,9.276000,9.586000,9.904000,10.233000,10.570000,10.918000,11.275000,11.643000,12.021000,12.410000,12.809000,13.219000,13.641000,14.074000,14.517000,14.973000,15.442000,15.995000,16.562000,17.147000,17.747000,18.365000,18.997000,19.647000,20.314000,20.998000,21.088000,21.177000,21.266000,21.355000,21.444000,21.534000,21.624000,21.714000,21.805000,21.895000,21.986000,22.078000,22.169000,22.261000,22.353000,22.500000,22.703000,22.907000,23.113000,23.320000,23.528000,23.737000,23.948000,24.160000,24.373000,24.587000,24.803000,25.020000,25.250000,25.495000,25.754000,26.026000,26.314000,26.616000,26.933000,27.265000,NaN
3,Africa Western and Central,AFW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,14.710006,15.094445,15.487932,15.900682,16.331319,16.779793,17.208682,17.652804,18.110817,18.581334,19.051229,19.590432,20.145372,20.710427,21.287396,21.873965,22.476171,23.039911,23.604732,24.083919,24.568479,25.176252,25.782009,26.393223,27.034553,27.716723,28.391322,29.057774,29.713126,30.353574,30.960098,31.401177,31.829516,32.252561,32.661719,33.065090,33.474223,33.929861,34.397143,34.868169,35.341698,35.951035,36.562771,37.183114,37.810952,38.448379,39.094612,39.738591,40.379509,41.023392,41.672423,42.316426,42.956838,43.587953,44.218278,44.849099,45.473850,46.094137,46.709753,47.322617,47.931021,48.531971,49.129808,49.711184,50.280934,NaN
4,Angola,AGO,Urban population (% of total population),SP.URB.TOTL.IN.ZS,10.435000,10.798000,11.204000,11.624000,12.058000,12.504000,12.965000,13.441000,13.932000,14.436000,14.957000,15.632000,16.455000,17.310000,18.202000,19.128000,20.092000,21.088000,22.122000,23.192000,24.298000,25.437000,26.612000,27.821000,29.065000,30.338000,31.643000,32.978000,34.343000,35.731000,37.144000,38.580000,40.039000,41.511000,43.000000,44.169000,45.346000,46.525000,47.710000,48.897000,50.087000,51.274000,52.461000,53.645000,54.827000,56.000000,56.764000,57.524000,58.282000,59.034000,59.783000,60.528000,61.268000,62.002000,62.731000,63.446000,64.149000,64.839000,65.514000,66.177000,66.825000,67.460000,68.081000,68.688000,69.281000,NaN

In [13]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in urban.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
urban = urban[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
urban = urban.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {urban.shape}")
urban.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,46.717000,46.339000,45.972000,45.606000,45.240000,44.875000,44.511000,44.147000,43.783000,43.421000,43.059000,42.940000,42.957000,42.990000,43.041000,43.108000,43.192000,43.293000,43.411000,43.546000,43.697000,43.866000,44.052000,44.254000
1,Africa Eastern and Southern,AFE,28.813361,29.110011,29.423890,29.734870,30.048040,30.380995,30.704020,30.958245,31.362783,31.774237,32.195595,32.628069,33.052742,33.496557,33.959633,34.447281,34.919544,35.396289,35.893398,36.384272,36.884034,37.393633,37.909012,38.424898
2,Afghanistan,AFG,22.078000,22.169000,22.261000,22.353000,22.500000,22.703000,22.907000,23.113000,23.320000,23.528000,23.737000,23.948000,24.160000,24.373000,24.587000,24.803000,25.020000,25.250000,25.495000,25.754000,26.026000,26.314000,26.616000,26.933000
3,Africa Western and Central,AFW,35.341698,35.951035,36.562771,37.183114,37.810952,38.448379,39.094612,39.738591,40.379509,41.023392,41.672423,42.316426,42.956838,43.587953,44.218278,44.849099,45.473850,46.094137,46.709753,47.322617,47.931021,48.531971,49.129808,49.711184
4,Angola,AGO,50.087000,51.274000,52.461000,53.645000,54.827000,56.000000,56.764000,57.524000,58.282000,59.034000,59.783000,60.528000,61.268000,62.002000,62.731000,63.446000,64.149000,64.839000,65.514000,66.177000,66.825000,67.460000,68.081000,68.688000

##  Tarif douanier moyens

In [15]:
douane=pd.read_csv("../data_raw\API_TM.TAX.MRCH.SM.AR.ZS_DS2_en_csv_v2_126349.csv",skiprows=4)
douane.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Tariff rate, applied, simple mean, all products (%)",TM.TAX.MRCH.SM.AR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.20,10.13,10.16,NaN,9.77,10.27,9.99,10.01,10.92,NaN,9.98,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Tariff rate, applied, simple mean, all products (%)",TM.TAX.MRCH.SM.AR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"Tariff rate, applied, simple mean, all products (%)",TM.TAX.MRCH.SM.AR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.86,NaN,6.16,6.18,6.47,NaN,NaN,NaN,6.95,6.95,NaN,NaN,NaN,NaN,8.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Tariff rate, applied, simple mean, all products (%)",TM.TAX.MRCH.SM.AR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,"Tariff rate, applied, simple mean, all products (%)",TM.TAX.MRCH.SM.AR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.21,NaN,8.19,7.98,7.98,NaN,7.81,7.77,7.91,7.84,7.73,7.70,11.19,10.91,10.90,NaN,8.54,8.65,10.51,12.03,11.59,NaN,NaN,NaN

In [16]:
# 2. Identifier les colonnes d'années disponibles
annees = [col for col in douane.columns if col.isdigit()]

# 3. Filtrer les années entre 2000 et 2023
annees_filtrees = [a for a in annees if 2000 <= int(a) <= 2023]

# 4. Garder les colonnes principales + années filtrées
colonnes_a_garder = ['Country Name', 'Country Code'] + annees_filtrees
douane = douane[colonnes_a_garder]

# 5. Renommer les colonnes pour simplifier
douane = douane.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})

print(f"Dimensions : {douane.shape}")
douane.head()

Dimensions : (266, 26)

,Country,ISO3,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.20,10.13,10.16,NaN,9.77,10.27,9.99,10.01,10.92,NaN,9.98,NaN,NaN
1,Africa Eastern and Southern,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,3.86,NaN,6.16,6.18,6.47,NaN,NaN,NaN,6.95,6.95,NaN,NaN,NaN,NaN,8.38,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,NaN,NaN,8.21,NaN,8.19,7.98,7.98,NaN,7.81,7.77,7.91,7.84,7.73,7.70,11.19,10.91,10.90,NaN,8.54,8.65,10.51,12.03,11.59,NaN

##  Equilibre alimentaire volailles

In [17]:
fbs = pd.read_csv("../data_raw/food_balances_poultry.csv")

# Sélectionner les éléments utiles
elements = ["Production", "Import quantity", "Export quantity", "Food supply (kg/capita/yr)"]
fbs = fbs[fbs["Element"].isin(elements)]

# Garder uniquement 2023
fbs = fbs[fbs["Year"] == 2022]

# Garder les colonnes importantes
fbs = fbs[["Area", "Element", "Value"]]
fbs.head()

            Area          Element  Value
165  Afghanistan       Production   29.0
166  Afghanistan  Import quantity    7.0
168  Afghanistan  Export quantity    0.0
355      Albania       Production   18.0
356      Albania  Import quantity   47.0

In [18]:
# Transformer les éléments en colonnes
fbs_2022 = fbs.pivot(index="Area", columns="Element", values="Value").reset_index()

# Vérification
print(f"Année utilisée : 2022")
fbs_2022.head()

Année utilisée : 2022

Element                 Area  Export quantity  Import quantity  Production
0                Afghanistan              0.0              7.0        29.0
1                    Albania              NaN             47.0        18.0
2                    Algeria              0.0              0.0       443.0
3                     Angola              0.0            316.0        57.0
4        Antigua and Barbuda              0.0              7.0         0.0

##  Stocks Volailles vivantes

In [19]:
livestock = pd.read_csv("../data_raw/livestock_production.csv")

print(livestock["Item"].unique()[:10])
print(livestock["Element"].unique()[:10])

['Chickens' 'Meat of chickens, fresh or chilled']
['Stocks' 'Yield/Carcass Weight' 'Production'
 'Producing Animals/Slaughtered']

In [20]:
livestock= livestock[livestock["Year"] == 2022]
livestock= livestock[["Area", "Element", "Year", "Unit", "Value"]]
livestock_2022= livestock.pivot(index="Area", columns="Element", values="Value").reset_index()
livestock_2022.head()

Element,Area,Producing Animals/Slaughtered,Production,Stocks,Yield/Carcass Weight
0,Afghanistan,33792.0,28503.14,13140.0,843.0
1,Albania,10646.0,16335.57,4999.0,1534.0
2,Algeria,372298.0,407744.31,196079.0,1095.0
3,Angola,54707.0,57177.38,44590.0,1045.0
4,Antigua and Barbuda,74.0,88.31,158.0,1200.0

##  Dépenses totales des Menages

In [21]:
# 1) Charger le fichier
menage = pd.read_csv("../data_raw\API_NE.CON.PRVT.PC.KD_DS2_en_csv_v2_6439.csv",skiprows=4)

# Renommer proprement les colonnes utiles
menage = menage.rename(columns={
    "Country Name": "Country",
    "Country Code": "ISO3"
})

# Garder uniquement Country, ISO3 et 2022
menage_2022 = menage[["Country", "ISO3", "2022"]].copy()

# Renommer l'indicateur
menage_2022 = menage_2022.rename(columns={
    "2022": "hfce_per_capita_usd_const2015"
})

# Nettoyage : enlever les lignes vides
menage_2022 = menage_2022.dropna(subset=["hfce_per_capita_usd_const2015"])

# Vérifier doublons
menage_2022 = menage_2022.drop_duplicates(subset=["ISO3"], keep="first")

menage_2022.head()

                       Country ISO3  hfce_per_capita_usd_const2015
1  Africa Eastern and Southern  AFE                     957.561668
4                       Angola  AGO                    1265.349090
5                      Albania  ALB                    3719.784469
7                   Arab World  ARB                    3385.814713
8         United Arab Emirates  ARE                   20888.477721

##  Pollution agricole

In [22]:
# Charger le fichier
n2o = pd.read_csv("../data_raw/per-capita-nitrous-oxide-agriculture.csv")

# 2Vérifier la structure
print(n2o.head())
print(n2o["Year"].max())  # juste informatif

# Garder uniquement l'année 2022
if 2022 in n2o["Year"].unique():
    n2o_2022 = n2o[n2o["Year"] == 2022]
else:
    print("Attention : pas de données disponibles pour 2022. Aucune ligne filtrée.")

# Garder les colonnes utiles
n2o_2022 = n2o_2022[["Entity", "Code", "Per capita nitrous oxide emissions from agriculture"]]

# Renommer pour standardiser
n2o_2022 = n2o_2022.rename(columns={
    "Entity": "Country",
    "Code": "ISO3",
    "Per capita nitrous oxide emissions from agriculture": "emissions_agri_pc"
})

n2o_2022.head()

        Entity Code  Year  Per capita nitrous oxide emissions from agriculture
0  Afghanistan  AFG  1990                                            200.07200
1  Afghanistan  AFG  1991                                            202.63293
2  Afghanistan  AFG  1992                                            182.99594
3  Afghanistan  AFG  1993                                            164.62366
4  Afghanistan  AFG  1994                                            142.14685
2022

         Country ISO3  emissions_agri_pc
32   Afghanistan  AFG           92.41268
65        Africa  NaN          266.76642
98       Albania  ALB          226.33923
131      Algeria  DZA          110.38452
164      Andorra  AND            0.00000

##  Prix Volailles

In [23]:
# Charger le fichier
prices = pd.read_csv("../data_raw/prices.csv")

# Garder uniquement la viande de poulet
prices = prices[prices["Item"] == "Meat of chickens, fresh or chilled"]

# Garder seulement l’élément "Producer Price (LCU/tonne)"
prices = prices[prices["Element"] == "Producer Price (LCU/tonne)"]

# Garder uniquement l'année 2022
if 2022 in prices["Year"].unique():
    prices_2022 = prices[prices["Year"] == 2022]
else:
    print("⚠️ Attention : pas de données disponibles pour 2022.")

# Garder les colonnes utiles
prices_2022 = prices_2022[["Area", "Value"]]

# Renommer les colonnes
prices_2022 = prices_2022.rename(columns={
    "Area": "Country",
    "Value": "poultry_price_lcu_t"
})

# Vérification
print("Année utilisée : 2022")
prices_2022.head()

Année utilisée : 2022

                 Country  poultry_price_lcu_t
12           Afghanistan             133465.2
90               Albania             525317.4
187              Algeria             330560.0
275  Antigua and Barbuda              12757.6
387            Argentina             116998.2

##  Part Bio Volailles

In [24]:
organic = pd.read_csv("../data_raw/share-of-arable-land-which-is-organic.csv")

# Garder uniquement l'année 2022
if 2022 in organic["Year"].unique():
    organic_2022 = organic[organic["Year"] == 2022]
else:
    print("⚠️ Attention : pas de données disponibles pour 2022.")

# Renommer les colonnes
organic_2022 = organic_2022.rename(columns={
    "Entity": "Country",
    "Code": "ISO3",
    "Agriculture area under organic agric. | 00006671 || Share in agricultural land | 007208 || percent": "organic_share"
})

# Supprimer la colonne Year
organic_2022 = organic_2022.drop(columns=["Year"], errors="ignore")

organic_2022.head()

           Country ISO3  organic_share
14     Afghanistan  AFG           0.00
33    Africa (FAO)  NaN           0.23
50         Albania  ALB           0.06
69         Algeria  DZA           0.00
88  Americas (FAO)  NaN           1.12

##  Commerce international

In [25]:
# Charger le fichier
trade = pd.read_csv("../data_raw/trade.csv")

# Garder uniquement le produit “Chickens”
trade = trade[trade["Item"] == "Chickens"]

# Garder uniquement les flux quantitatifs
elements = ["Import quantity", "Export quantity"]
trade = trade[trade["Element"].isin(elements)]

# Garder uniquement l'année 2022
if 2022 in trade["Year"].unique():
    trade = trade[trade["Year"] == 2022]
else:
    print("⚠️ Attention : pas de données disponibles pour 2022.")

# Garder les colonnes utiles (sans Year ni Unit)
trade = trade[["Area", "Element", "Value"]]

# Transformer les éléments en colonnes
trade_2022 = trade.pivot(index="Area", columns="Element", values="Value").reset_index()

# Renommer pour standardiser
trade_2022 = trade_2022.rename(columns={
    "Area": "Country",
    "Import quantity": "poultry_import_t",
    "Export quantity": "poultry_export_t"
})

# Vérification
print("Année utilisée : 2022")
trade_2022.head()

Année utilisée : 2022

Element              Country  poultry_export_t  poultry_import_t
0                Afghanistan               NaN           11927.0
1                    Albania               NaN            8743.0
2                    Algeria               NaN            4619.0
3                     Angola               1.0              35.0
4        Antigua and Barbuda               1.0               1.0

##  Dispo Alimentaire

In [26]:
# 1) Charger
fbs_raw = pd.read_csv("../data_raw/dispo_alimentaire.csv")

# Harmoniser maïs
fbs_raw["Item"] = fbs_raw["Item"].replace({
    "Maize": "Maize and products"
})

# 2) Produits à garder
items_keep = [
    "Wheat and products",
    "Rice (milled equivalent)",
    "Maize and products"
]

# 3) Éléments à garder
elements_keep = {
    "Production": "production",
    "Import quantity": "import",
    "Export quantity": "export",
    "Food supply (kg/capita/yr)": "supply_kg_ph"
}

# 4) Filtrer
fbs = fbs_raw[
    fbs_raw["Item"].isin(items_keep) &
    fbs_raw["Element"].isin(elements_keep.keys())
][["Area", "Year", "Item", "Element", "Value"]]

# 🔥 Garder uniquement 2022
if 2022 in fbs["Year"].unique():
    fbs = fbs[fbs["Year"] == 2022]
else:
    print("⚠️ Pas d'année 2022 dans ce fichier.")

# 5) Renommer les éléments
fbs["Element_simple"] = fbs["Element"].map(elements_keep)

# 6) Créer un nom de variable par ligne
fbs["varname"] = (
    fbs["Item"].str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
    .str.replace("-", "_")
    .str.replace("/", "_")
    + "_" +
    fbs["Element_simple"]
)

# 7) Pivot
fbs_simple_pivot = fbs.pivot_table(
    index=["Area"],      # 👈 plus de Year ici
    columns="varname",
    values="Value",
    aggfunc="first"
).reset_index()

# 8) Agrégation
fbs_simple_pivot["cereal_production_t"] = fbs_simple_pivot.filter(regex="production$").sum(axis=1)
fbs_simple_pivot["cereal_import_t"]     = fbs_simple_pivot.filter(regex="import$").sum(axis=1)
fbs_simple_pivot["cereal_export_t"]     = fbs_simple_pivot.filter(regex="export$").sum(axis=1)
fbs_simple_pivot["cereal_supply_kg_ph"] = fbs_simple_pivot.filter(regex="supply_kg_ph$").sum(axis=1)

# 9) Finaliser (🔥 suppression de Year)
fbs_cereal_final = fbs_simple_pivot[[
    "Area",
    "cereal_production_t",
    "cereal_import_t",
    "cereal_export_t",
    "cereal_supply_kg_ph"
]].rename(columns={"Area": "Country"})

# 10) Convertir en numérique
numeric_cols = [
    "cereal_production_t",
    "cereal_import_t",
    "cereal_export_t",
    "cereal_supply_kg_ph"
]

for col in numeric_cols:
    fbs_cereal_final[col] = pd.to_numeric(fbs_cereal_final[col], errors="coerce")

fbs_cereal_final.head()

varname,Country,cereal_production_t,cereal_import_t,cereal_export_t,cereal_supply_kg_ph
0,Afghanistan,4114.0,3752.0,0.0,0.0
1,Albania,634.0,340.0,14.0,0.0
2,Algeria,3011.0,10863.0,90.0,0.0
3,Angola,3098.0,1012.0,14.0,0.0
4,Antigua and Barbuda,0.0,11.0,0.0,0.0

## Vérifier les pays et les Annéees

In [27]:
# Chargement des données brutes 

gdp_raw    = pd.read_csv("../data_raw\API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_129964.csv", skiprows=4)
log_raw    = pd.read_csv("../data_raw/API_LP.LPI.OVRL.XQ_DS2_en_csv_v2_6417.csv", skiprows=4)
stab_raw   = pd.read_csv("../data_raw\API_PV.EST_DS2_en_csv_v2_126909.csv", skiprows=4)
tariff_raw = pd.read_csv("../data_raw\API_TM.TAX.MRCH.SM.AR.ZS_DS2_en_csv_v2_126349.csv", skiprows=4)
urban_raw  = pd.read_csv("../data_raw/API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_129596.csv", skiprows=4)
pop_raw    = pd.read_csv("../data_raw/API_SP.POP.TOTL_DS2_en_csv_v2_130083.csv", skiprows=4)
menage_raw   = pd.read_csv("../data_raw\API_NE.CON.PRVT.PC.KD_DS2_en_csv_v2_6439.csv", skiprows=4)    

# Fonction générique pour transformer les fichiers World Bank du format large (colonnes = années)
# en format long (année en ligne). var_name = nom de variable (GDP, stabilité, etc.)
def wb_long(df, var_name):
    year_cols = [c for c in df.columns if c.isdigit()]
    # Sélection des colonnes correspondant aux années (colonnes numériques)
    # Transformation wide → long
    df_long = df.melt(
        id_vars=["Country Name", "Country Code"],
        value_vars=year_cols,
        var_name="Year",
        value_name=var_name
    )
    # Conversion correcte des années
    df_long["Year"] = df_long["Year"].astype(int)
    # Renommage pour harmonisation
    df_long = df_long.rename(columns={
        "Country Name": "Country",
        "Country Code": "ISO3"
    })
    return df_long

# Conversion de toutes les sources WB au format long uniforme
gdp_long    = wb_long(gdp_raw,    "gdp_ppp_pc")
log_long    = wb_long(log_raw,    "logistics_index")
stab_long   = wb_long(stab_raw,   "political_stability")
tariff_long = wb_long(tariff_raw, "tariff_rate")
urban_long  = wb_long(urban_raw,  "urban_rate")
pop_long    = wb_long(pop_raw,    "population")

In [28]:
# Chargement des données FAO & OWID (déjà en format long)
fbs_raw      = pd.read_csv("../data_raw/food_balances_poultry.csv")      # Area, Year
livestock_raw= pd.read_csv("../data_raw/livestock_production.csv")      # Area, Year
trade_raw    = pd.read_csv("../data_raw/trade.csv")                     # Area, Year
prices_raw   = pd.read_csv("../data_raw/prices.csv")                    # Area, Year
                

organic_raw  = pd.read_csv("../data_raw/share-of-arable-land-which-is-organic.csv")  # Entity, Year
n2o_raw      = pd.read_csv("../data_raw/per-capita-nitrous-oxide-agriculture.csv")   # Entity, Year

fbs_cereal_df = fbs_cereal_final.copy()

In [29]:
# Assemblage dans un dictionnaire pour automatiser l'analyse de couverture
# Chaque entrée contient au minimum : colonne pays + année
dfs = {
    "FAO_food_balances": fbs_raw[["Area", "Year"]],
    "FAO_livestock":     livestock_raw[["Area", "Year"]],
    "FAO_trade":         trade_raw[["Area", "Year"]],
    "FAO_prices":        prices_raw[["Area", "Year"]],
    

    "FAO_cereals":       fbs_cereal_final[["Country"]],  

    "OWID_organic":      organic_raw[["Entity", "Year"]],
    "OWID_n2o":          n2o_raw[["Entity", "Year"]],

    "WB_gdp":            gdp_long[["Country", "Year"]],
    "WB_logistics":      log_long[["Country", "Year"]],
    "WB_stability":      stab_long[["Country", "Year"]],
    "WB_tariff":         tariff_long[["Country", "Year"]],
    "WB_urban":          urban_long[["Country", "Year"]],
    "WB_population":     pop_long[["Country", "Year"]],
}

# Fonction pour calculer, pour chaque année, le nombre de pays présents dans une source
def coverage(df, name):
    # deviner la colonne pays
    if "Country" in df.columns:
        country_col = "Country"
    elif "Area" in df.columns:
        country_col = "Area"
    elif "Entity" in df.columns:
        country_col = "Entity"
    elif "Enquête" in df.columns:
        country_col = "Enquête"   # on comptera les enquêtes (1 par pays/année)
    else:
        print(f"{name}: pas de colonne pays reconnue")
        return pd.DataFrame()
    # Calcul : nb de pays uniques par année
    cov = (
        df.groupby("Year")[country_col]
        .nunique()
        .reset_index()
        .rename(columns={country_col: "nb_pays"})
    )
    cov["source"] = name
    return cov

In [30]:
# Calcul de la couverture pour toutes les sources
all_cov = []

for name, df in dfs.items():
    try:
        cov = coverage(df, name)
        all_cov.append(cov)
    except Exception as e:
        print(f"⚠️ Erreur pour {name}: {e}")

coverage_all = pd.concat(all_cov, ignore_index=True)

# Résumé : années min/max couvertes par chaque source
print(
    coverage_all
    .groupby("source")["Year"]
    .agg(["min", "max"])
    .sort_values("max")
)

⚠️ Erreur pour FAO_cereals: 'Year'
                    min   max
source
OWID_organic       2004  2022
OWID_n2o           1990  2022
FAO_food_balances  2010  2023
FAO_livestock      2010  2023
FAO_trade          2010  2023
FAO_prices         2010  2023
WB_gdp             1960  2024
WB_logistics       1960  2024
WB_population      1960  2024
WB_stability       1960  2024
WB_tariff          1960  2024
WB_urban           1960  2024

In [31]:
# Moyenne du nombre de pays couverts par année
summary = (
    coverage_all
    .groupby("Year")["nb_pays"]
    .mean()
    .reset_index()
    .sort_values("Year", ascending=False)
)

summary.head(15)

    Year     nb_pays
64  2024  266.000000
63  2023  231.600000
62  2022  226.500000
61  2021  226.583333
60  2020  226.500000
59  2019  227.083333
58  2018  226.833333
57  2017  226.250000
56  2016  226.166667
55  2015  225.833333
54  2014  225.833333
53  2013  225.416667
52  2012  225.000000
51  2011  224.833333
50  2010  224.500000

In [32]:
# Tableau pivot année × source → nb de pays
pivot = (
    coverage_all
    .pivot(index="Year", columns="source", values="nb_pays")
    .sort_index(ascending=False)
)

pivot.head(10)

# Indicateurs supplémentaires : nombre de sources avec <100 pays
pivot["nb_sources_sous_100"] = (pivot < 100).sum(axis=1)
pivot["nb_sources_total"] = pivot.notna().sum(axis=1)

pivot["pct_sources_sous_100"] = pivot["nb_sources_sous_100"] / pivot["nb_sources_total"] * 100

# Fusion avec la moyenne du nombre de pays
summary = (
    coverage_all
    .groupby("Year")["nb_pays"]
    .mean()
    .rename("moyenne_nb_pays")
)

pivot = pivot.merge(summary, on="Year")

pivot.head(10)

,FAO_food_balances,FAO_livestock,FAO_prices,FAO_trade,OWID_n2o,OWID_organic,WB_gdp,WB_logistics,WB_population,WB_stability,WB_tariff,WB_urban,nb_sources_sous_100,nb_sources_total,pct_sources_sous_100,moyenne_nb_pays
Year,,,,,,,,,,,,,,,,
2024,NaN,NaN,NaN,NaN,NaN,NaN,266.0,266.0,266.0,266.0,266.0,266.0,0,7,0.0,266.000000
2023,177.0,196.0,151.0,196.0,NaN,NaN,266.0,266.0,266.0,266.0,266.0,266.0,0,11,0.0,231.600000
2022,177.0,196.0,151.0,195.0,205.0,198.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.500000
2021,177.0,196.0,150.0,195.0,205.0,200.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.583333
2020,177.0,196.0,150.0,196.0,205.0,198.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.500000
2019,178.0,196.0,150.0,196.0,205.0,204.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,227.083333
2018,171.0,196.0,151.0,196.0,205.0,207.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.833333
2017,171.0,196.0,151.0,196.0,205.0,200.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.250000
2016,171.0,196.0,151.0,196.0,205.0,199.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,226.166667
2015,171.0,196.0,151.0,195.0,205.0,196.0,266.0,266.0,266.0,266.0,266.0,266.0,0,13,0.0,225.833333

## Test Année 2022

In [33]:
# def detect_country_column(df):
#     if "Country" in df.columns:
#         return "Country"
#     if "Area" in df.columns:
#         return "Area"
#     if "Entity" in df.columns:
#         return "Entity"
#     if "Enquête" in df.columns:
#         return "Enquête"
#     return None

# countries_2022 = {}

# for name, df in dfs.items():
#     col = detect_country_column(df)
#     if col is None:
#         print(f"⚠️ Aucun champ pays reconnu pour {name}")
#         continue
    
#     # filtrer sur 2022
#     df_2022 = df[df["Year"] == 2022]
    
#     # récupérer les pays uniques
#     countries = set(df_2022[col].dropna().unique())
#     countries_2022[name] = countries
    
#     print(f"{name} : {len(countries)} pays en 2022")

In [34]:
# common_2022 = set.intersection(*countries_2022.values())
# print("Pays communs en 2022 :", len(common_2022))

## Nettoyage et jointure des différents fichiers de la Banque Mondiale

Indicateur de performance logistique

In [35]:
# Garder uniquement Country, ISO3 et 2022
logistique_2022 = logistique[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
logistique_2022 = logistique_2022.rename(columns={'2022': 'indicateur_perf_logistique'})


logistique_2022.head()

                       Country ISO3  indicateur_perf_logistique
0                        Aruba  ABW                         NaN
1  Africa Eastern and Southern  AFE                    2.618182
2                  Afghanistan  AFG                    1.900000
3   Africa Western and Central  AFW                    2.473333
4                       Angola  AGO                    2.100000

In [36]:
logistique_2022['indicateur_perf_logistique'].count()

np.int64(186)

PIB par habitant

In [37]:
# Garder uniquement Country, ISO3 et 2022
pib_2022 = pib[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
pib_2022 = pib_2022.rename(columns={'2022': 'pib_par_hab'})


pib_2022.head()

                       Country ISO3   pib_par_hab
0                        Aruba  ABW  41649.450792
1  Africa Eastern and Southern  AFE   4229.086486
2                  Afghanistan  AFG   2122.995815
3   Africa Western and Central  AFW   5169.145547
4                       Angola  AGO   7924.888806

In [38]:
pib_2022['pib_par_hab'].count()
pib_2022['Country'].nunique()

266

Indice de stabilité politique

In [39]:
# Garder uniquement Country, ISO3 et 2022
stabilite_2022 = stabilite[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
stabilite_2022 = stabilite_2022.rename(columns={'2022': 'stab_politique'})


stabilite_2022.head()

                       Country ISO3  stab_politique
0                        Aruba  ABW        1.483080
1  Africa Eastern and Southern  AFE             NaN
2                  Afghanistan  AFG       -2.544956
3   Africa Western and Central  AFW             NaN
4                       Angola  AGO       -0.630109

In [40]:
stabilite_2022['stab_politique'].count()

np.int64(205)

Population totale

In [41]:
# Garder uniquement Country, ISO3 et 2022
pop_2022 = pop[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
pop_2022 = pop_2022.rename(columns={'2022': 'population'})


pop_2022.head()

                       Country ISO3   population
0                        Aruba  ABW     107310.0
1  Africa Eastern and Southern  AFE  731821393.0
2                  Afghanistan  AFG   40578842.0
3   Africa Western and Central  AFW  497387180.0
4                       Angola  AGO   35635029.0

Taux d'urbanisation

In [42]:
# Garder uniquement Country, ISO3 et 2022
urban_2022 = urban[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
urban_2022 = urban_2022.rename(columns={'2022': 'tx_urbanisation'})


urban_2022.head()

                       Country ISO3  tx_urbanisation
0                        Aruba  ABW        44.052000
1  Africa Eastern and Southern  AFE        37.909012
2                  Afghanistan  AFG        26.616000
3   Africa Western and Central  AFW        49.129808
4                       Angola  AGO        68.081000

Tarif douanier moyen

In [43]:
# Garder uniquement Country, ISO3 et 2022
douane_2022 = douane[['Country', 'ISO3', '2022']].copy()

# Renommer la colonne
douane_2022 = douane_2022.rename(columns={'2022': 'tarif_douanier_moyen'})

douane_2022.head()

                       Country ISO3  tarif_douanier_moyen
0                        Aruba  ABW                   NaN
1  Africa Eastern and Southern  AFE                   NaN
2                  Afghanistan  AFG                   NaN
3   Africa Western and Central  AFW                   NaN
4                       Angola  AGO                 11.59

Pollution Agricole

In [44]:
n2o_2022.head()

         Country ISO3  emissions_agri_pc
32   Afghanistan  AFG           92.41268
65        Africa  NaN          266.76642
98       Albania  ALB          226.33923
131      Algeria  DZA          110.38452
164      Andorra  AND            0.00000

Part Bio Volailles

In [45]:
organic_2022.head()

           Country ISO3  organic_share
14     Afghanistan  AFG           0.00
33    Africa (FAO)  NaN           0.23
50         Albania  ALB           0.06
69         Algeria  DZA           0.00
88  Americas (FAO)  NaN           1.12

menage

In [46]:
menage_2022.head()

                       Country ISO3  hfce_per_capita_usd_const2015
1  Africa Eastern and Southern  AFE                     957.561668
4                       Angola  AGO                    1265.349090
5                      Albania  ALB                    3719.784469
7                   Arab World  ARB                    3385.814713
8         United Arab Emirates  ARE                   20888.477721

Jointure entre les différents documents de la Banque Mondiale

In [47]:
for name, df in {
    "logistique": logistique_2022,
    "pib": pib_2022,
    "stabilite": stabilite_2022,
    "pop": pop_2022,
    "urban": urban_2022,
    "douane": douane_2022,
    "n2o": n2o_2022,
    "organic": organic_2022,
    "menage": menage_2022
}.items():
    print(name, df["ISO3"].nunique())

logistique 266
pib 266
stabilite 266
pop 266
urban 266
douane 266
n2o 194
organic 168
menage 209

In [48]:
set_n2o = set(n2o_2022["ISO3"])
set_log = set(logistique_2022["ISO3"])

print("Pays présents dans n2o mais pas dans logistique :")
print(set_n2o - set_log)

set_org = set(organic_2022["ISO3"])

print("Pays présents dans organic mais pas dans logistique :")
print(set_org - set_log)

Pays présents dans n2o mais pas dans logistique :
{'NIU', 'OWID_WRL', 'COK', nan}
Pays présents dans organic mais pas dans logistique :
{'NIU', 'GUF', 'OWID_WRL', 'REU', 'OWID_MNS', 'MTQ', 'FLK', 'MYT', 'OWID_PYA', 'OWID_CIS', nan, 'GLP', 'COK', 'TWN'}

In [49]:
def keep_real_countries(df):
    # Garder seulement les ISO3 non-na
    df = df.dropna(subset=["ISO3"]).copy()
    # Garder uniquement les codes ISO3 valides (3 lettres A-Z)
    df = df[df["ISO3"].str.fullmatch(r"[A-Z]{3}")]
    return df

logistique_2022 = keep_real_countries(logistique_2022)
pib_2022 = keep_real_countries(pib_2022)
stabilite_2022 = keep_real_countries(stabilite_2022)
pop_2022 = keep_real_countries(pop_2022)
urban_2022 = keep_real_countries(urban_2022)
douane_2022 = keep_real_countries(douane_2022)
n2o_2022 = keep_real_countries(n2o_2022)
organic_2022 = keep_real_countries(organic_2022)
menage_2022 = keep_real_countries(menage_2022)

In [50]:
df_BAO = logistique_2022.copy()

dfs_to_merge = [
    pib_2022, stabilite_2022, pop_2022,
    urban_2022, douane_2022, n2o_2022,
    organic_2022, menage_2022
]

# errors='ignore'
for df in dfs_to_merge:
    df_BAO = df_BAO.merge(
        df.drop(columns=['Country']),
        on='ISO3',
        how='outer'
    )

In [51]:
df_BAO['ISO3'].nunique(), len(df_BAO)
df_BAO.to_csv("../data_clean/df_BAO.csv", index=False, encoding="utf-8")

Vérifier que je n'ai pas perdu de données?

## Nettoyage et jointure des différents fichiers de la FAO

Equilibre Alimentaire

In [52]:

fbs_2022 = fbs_2022.rename(columns={
    "Area": "Country",
    "Export quantity": "food_balance_export_quantity",
    "Import quantity": "food_balance_import_quantity",
    "Production": "food_balance_production"
})

fbs_2022.head()

Element,Country,food_balance_export_quantity,food_balance_import_quantity,food_balance_production
0,Afghanistan,0.0,7.0,29.0
1,Albania,NaN,47.0,18.0
2,Algeria,0.0,0.0,443.0
3,Angola,0.0,316.0,57.0
4,Antigua and Barbuda,0.0,7.0,0.0

Stock vollailles vivantes

In [53]:
livestock_2022 = livestock_2022.rename(columns={
    "Area": "Country",
    "Producing Animals/Slaughtered	": "livestock_producing_animals_slaugh",
    "Production": "livestock_production",
    "Stocks": "livestock_stock",
    "Yield/Carcass Weight": "livestock_yield_carcass_weight"
})

livestock_2022.head()

Element,Country,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight
0,Afghanistan,33792.0,28503.14,13140.0,843.0
1,Albania,10646.0,16335.57,4999.0,1534.0
2,Algeria,372298.0,407744.31,196079.0,1095.0
3,Angola,54707.0,57177.38,44590.0,1045.0
4,Antigua and Barbuda,74.0,88.31,158.0,1200.0

Prix volailles

In [54]:
prices_2022.head()

                 Country  poultry_price_lcu_t
12           Afghanistan             133465.2
90               Albania             525317.4
187              Algeria             330560.0
275  Antigua and Barbuda              12757.6
387            Argentina             116998.2

Commerce international

In [55]:
trade_2022.head()

Element              Country  poultry_export_t  poultry_import_t
0                Afghanistan               NaN           11927.0
1                    Albania               NaN            8743.0
2                    Algeria               NaN            4619.0
3                     Angola               1.0              35.0
4        Antigua and Barbuda               1.0               1.0

Dispo amlimentaire

In [56]:

fbs_cereal_final=fbs_cereal_final.drop(columns=["cereal_supply_kg_ph"])
fbs_cereal_final.head()

varname,Country,cereal_production_t,cereal_import_t,cereal_export_t
0,Afghanistan,4114.0,3752.0,0.0
1,Albania,634.0,340.0,14.0
2,Algeria,3011.0,10863.0,90.0
3,Angola,3098.0,1012.0,14.0
4,Antigua and Barbuda,0.0,11.0,0.0

Jointure

In [57]:
# On part du premier DF comme base
df_FAO = fbs_2022.copy()

# Liste des autres DFs
dfs_to_merge = [livestock_2022, prices_2022, trade_2022, fbs_cereal_final]

# Boucle de jointure
for df in dfs_to_merge:
    df_FAO = df_FAO.merge(df, on="Country", how="outer")

# Résultat final
df_FAO.head()

,Country,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
0,Afghanistan,0.0,7.0,29.0,33792.0,28503.14,13140.0,843.0,133465.2,NaN,11927.0,4114.0,3752.0,0.0
1,Albania,NaN,47.0,18.0,10646.0,16335.57,4999.0,1534.0,525317.4,NaN,8743.0,634.0,340.0,14.0
2,Algeria,0.0,0.0,443.0,372298.0,407744.31,196079.0,1095.0,330560.0,NaN,4619.0,3011.0,10863.0,90.0
3,Angola,0.0,316.0,57.0,54707.0,57177.38,44590.0,1045.0,NaN,1.0,35.0,3098.0,1012.0,14.0
4,Antigua and Barbuda,0.0,7.0,0.0,74.0,88.31,158.0,1200.0,12757.6,1.0,1.0,0.0,11.0,0.0

In [58]:
# Copier pour éviter de modifier l’original
df_FAO_iso = df_FAO.copy()

# Créer la colonne ISO3
df_FAO_iso["ISO3"] = coco.convert(
    names=df_FAO_iso["Country"],
    to="ISO3",
    not_found=None
)

# Réordonner les colonnes : mettre ISO3 juste après Country
cols = df_FAO_iso.columns.tolist()

# Trouver l'index de Country
idx = cols.index("Country")

# Nouvelle liste de colonnes
new_cols = cols[:idx+1] + ["ISO3"] + [c for c in cols if c not in ("Country", "ISO3")]

# Appliquer le nouvel ordre
df_FAO_iso = df_FAO_iso[new_cols]

df_FAO_iso.head()

More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of
More than one regular expression match for China, Taiwan Province of

,Country,ISO3,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
0,Afghanistan,AFG,0.0,7.0,29.0,33792.0,28503.14,13140.0,843.0,133465.2,NaN,11927.0,4114.0,3752.0,0.0
1,Albania,ALB,NaN,47.0,18.0,10646.0,16335.57,4999.0,1534.0,525317.4,NaN,8743.0,634.0,340.0,14.0
2,Algeria,DZA,0.0,0.0,443.0,372298.0,407744.31,196079.0,1095.0,330560.0,NaN,4619.0,3011.0,10863.0,90.0
3,Angola,AGO,0.0,316.0,57.0,54707.0,57177.38,44590.0,1045.0,NaN,1.0,35.0,3098.0,1012.0,14.0
4,Antigua and Barbuda,ATG,0.0,7.0,0.0,74.0,88.31,158.0,1200.0,12757.6,1.0,1.0,0.0,11.0,0.0

In [59]:
#Pays non reconnu
df_FAO_iso[df_FAO_iso["ISO3"].isna()]["Country"].unique()

array([], dtype=object)

In [60]:
df_FAO_iso.to_csv("../data_clean/df_FAO.csv", index=False, encoding="utf-8")

## Comparer le remplissage de FAO et BAO

In [61]:
df_BAO.head()

,Country,ISO3,indicateur_perf_logistique,pib_par_hab,stab_politique,population,tx_urbanisation,tarif_douanier_moyen,emissions_agri_pc,organic_share,hfce_per_capita_usd_const2015
0,Aruba,ABW,NaN,41649.450792,1.483080,107310.0,44.052000,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,2.618182,4229.086486,NaN,731821393.0,37.909012,NaN,NaN,NaN,957.561668
2,Afghanistan,AFG,1.900000,2122.995815,-2.544956,40578842.0,26.616000,NaN,92.41268,0.0,NaN
3,Africa Western and Central,AFW,2.473333,5169.145547,NaN,497387180.0,49.129808,NaN,NaN,NaN,NaN
4,Angola,AGO,2.100000,7924.888806,-0.630109,35635029.0,68.081000,11.59,424.86288,NaN,1265.349090

In [62]:
df_FAO_iso.head()

,Country,ISO3,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
0,Afghanistan,AFG,0.0,7.0,29.0,33792.0,28503.14,13140.0,843.0,133465.2,NaN,11927.0,4114.0,3752.0,0.0
1,Albania,ALB,NaN,47.0,18.0,10646.0,16335.57,4999.0,1534.0,525317.4,NaN,8743.0,634.0,340.0,14.0
2,Algeria,DZA,0.0,0.0,443.0,372298.0,407744.31,196079.0,1095.0,330560.0,NaN,4619.0,3011.0,10863.0,90.0
3,Angola,AGO,0.0,316.0,57.0,54707.0,57177.38,44590.0,1045.0,NaN,1.0,35.0,3098.0,1012.0,14.0
4,Antigua and Barbuda,ATG,0.0,7.0,0.0,74.0,88.31,158.0,1200.0,12757.6,1.0,1.0,0.0,11.0,0.0

Jointure BAO et FAO

In [63]:
#Problème sur les ISO3 et correction
df_BAO["ISO3"].apply(type).unique()
df_FAO_iso["ISO3"].apply(type).unique()

def fix_iso3(x):
    if isinstance(x, list) and len(x) > 0:
        return x[0]        # garde la première valeur de la liste
    else:
        return x           # garde la valeur telle quelle si c'est déjà une string

df_FAO_iso["ISO3"] = df_FAO_iso["ISO3"].apply(fix_iso3)
df_BAO["ISO3"] = df_BAO["ISO3"].apply(fix_iso3)

In [64]:
df_merged = df_BAO.merge(
    df_FAO_iso,
    on="ISO3",
    how="left"   # left pour garder tous les pays BAO
)

df_merged.head()

,Country_x,ISO3,indicateur_perf_logistique,pib_par_hab,stab_politique,population,tx_urbanisation,tarif_douanier_moyen,emissions_agri_pc,organic_share,hfce_per_capita_usd_const2015,Country_y,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
0,Aruba,ABW,NaN,41649.450792,1.483080,107310.0,44.052000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,2.618182,4229.086486,NaN,731821393.0,37.909012,NaN,NaN,NaN,957.561668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1.900000,2122.995815,-2.544956,40578842.0,26.616000,NaN,92.41268,0.0,NaN,Afghanistan,0.0,7.0,29.0,33792.0,28503.14,13140.0,843.0,133465.2,NaN,11927.0,4114.0,3752.0,0.0
3,Africa Western and Central,AFW,2.473333,5169.145547,NaN,497387180.0,49.129808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,2.100000,7924.888806,-0.630109,35635029.0,68.081000,11.59,424.86288,NaN,1265.349090,Angola,0.0,316.0,57.0,54707.0,57177.38,44590.0,1045.0,NaN,1.0,35.0,3098.0,1012.0,14.0

In [65]:
print("Avant :", df_BAO.shape)
print("Après :", df_merged.shape)

Avant : (275, 11)
Après : (277, 25)

In [66]:
# Calcul du taux de remplissage pour chaque ligne
df_merged["taux_remplissage"] = df_merged.notna().mean(axis=1) * 100

# Arrondir pour lisibilité
df_merged["taux_remplissage"] = df_merged["taux_remplissage"].round(1)

df_merged.head()

,Country_x,ISO3,indicateur_perf_logistique,pib_par_hab,stab_politique,population,tx_urbanisation,tarif_douanier_moyen,emissions_agri_pc,organic_share,hfce_per_capita_usd_const2015,Country_y,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t,taux_remplissage
0,Aruba,ABW,NaN,41649.450792,1.483080,107310.0,44.052000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
1,Africa Eastern and Southern,AFE,2.618182,4229.086486,NaN,731821393.0,37.909012,NaN,NaN,NaN,957.561668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0
2,Afghanistan,AFG,1.900000,2122.995815,-2.544956,40578842.0,26.616000,NaN,92.41268,0.0,NaN,Afghanistan,0.0,7.0,29.0,33792.0,28503.14,13140.0,843.0,133465.2,NaN,11927.0,4114.0,3752.0,0.0,88.0
3,Africa Western and Central,AFW,2.473333,5169.145547,NaN,497387180.0,49.129808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
4,Angola,AGO,2.100000,7924.888806,-0.630109,35635029.0,68.081000,11.59,424.86288,NaN,1265.349090,Angola,0.0,316.0,57.0,54707.0,57177.38,44590.0,1045.0,NaN,1.0,35.0,3098.0,1012.0,14.0,92.0

In [67]:
nb_pays_80 = (df_merged["taux_remplissage"] > 80).sum()
print("Nombre de pays avec un taux de remplissage > 80% :", nb_pays_80)

Nombre de pays avec un taux de remplissage > 80% : 156

In [68]:
# Colonnes que tu veux mettre en premier
cols_first = ["Country_x", "taux_remplissage","nb_colonnes_remplies"]

# Colonnes restantes du DataFrame
cols_rest = [c for c in df_merged.columns if c not in cols_first]

# Ajouter la colonne nombre_colonnes_remplies
df_merged["nb_colonnes_remplies"] = df_merged.notna().sum(axis=1)

# Filtrer et réordonner
pays_80 = df_merged[df_merged["taux_remplissage"] > 80][
    cols_first + cols_rest
].sort_values("taux_remplissage", ascending=False).reset_index(drop=True)

pays_80.head()

,Country_x,taux_remplissage,nb_colonnes_remplies,ISO3,indicateur_perf_logistique,pib_par_hab,stab_politique,population,tx_urbanisation,tarif_douanier_moyen,emissions_agri_pc,organic_share,hfce_per_capita_usd_const2015,Country_y,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
0,Belgium,100.0,26,BEL,4.0,68157.834786,0.581982,11680210.0,98.153,1.95,175.23042,7.49,21959.173610,Belgium,525.0,309.0,450.0,297794.0,442020.00,53283.0,1484.0,1247.6,121147.0,109384.0,2352.0,9771.0,3460.0
1,Chile,100.0,26,CHL,3.0,30820.352697,0.132084,19553036.0,87.912,1.03,204.57184,1.76,9734.080367,Chile,188.0,174.0,769.0,300523.0,692847.28,57142.0,2305.0,1090660.8,0.0,448.0,1715.0,4077.0,70.0
2,Canada,100.0,26,CAN,4.0,63578.320195,0.780682,38935934.0,81.752,1.83,872.97530,2.75,26412.766573,Canada,151.0,206.0,1532.0,789394.0,1370800.00,171099.0,1737.0,2893.9,4547.0,31890.0,48895.0,8213.0,22936.0
3,Bosnia and Herzegovina,100.0,26,BIH,3.0,21117.283077,-0.483194,3204802.0,49.841,3.39,234.02382,0.11,4506.032565,Bosnia and Herzegovina,14.0,15.0,67.0,43537.0,67007.00,9299.0,1539.0,2263.0,6641.0,29708.0,1268.0,773.0,100.0
4,Switzerland,100.0,26,CHE,4.1,91326.131705,1.159745,8777088.0,74.092,3.16,143.30917,12.38,44877.858320,Switzerland,3.0,49.0,112.0,87825.0,109515.00,13109.0,1247.0,3527.0,1183.0,309.0,612.0,1606.0,184.0

In [69]:
pays_80["ISO3"].duplicated().sum()

np.int64(2)

In [70]:
pays_80[pays_80["ISO3"]=="CHN"]

,Country_x,taux_remplissage,nb_colonnes_remplies,ISO3,indicateur_perf_logistique,pib_par_hab,stab_politique,population,tx_urbanisation,tarif_douanier_moyen,emissions_agri_pc,organic_share,hfce_per_capita_usd_const2015,Country_y,food_balance_export_quantity,food_balance_import_quantity,food_balance_production,Producing Animals/Slaughtered,livestock_production,livestock_stock,livestock_yield_carcass_weight,poultry_price_lcu_t,poultry_export_t,poultry_import_t,cereal_production_t,cereal_import_t,cereal_export_t
27,China,100.0,26,CHN,3.7,23032.176627,-0.451277,1.412175e+09,63.56,5.36,200.46597,0.56,4647.963491,"China, mainland",719.0,1316.0,24430.0,11391735.0,14300000.00,5192978.0,1255.0,19072.0,112.0,2172.0,414923.0,34846.0,1006.0
58,China,96.0,25,CHN,3.7,23032.176627,-0.451277,1.412175e+09,63.56,5.36,200.46597,0.56,4647.963491,China,759.0,1871.0,25235.0,11802648.0,15000930.21,5298793.0,1271.0,NaN,112.0,8987.0,415178.0,41174.0,1204.0
96,China,92.0,24,CHN,3.7,23032.176627,-0.451277,1.412175e+09,63.56,5.36,200.46597,0.56,4647.963491,"China, Taiwan Province of",1.0,218.0,779.0,392399.0,675000.00,101080.0,1720.0,NaN,NaN,439.0,255.0,5709.0,131.0

In [71]:
pays_80 = pays_80[~pays_80["Country_y"].isin(["China, mainland", "China, Taiwan Province of"])]

In [72]:
pays_80["ISO3"].duplicated().sum()

np.int64(0)

In [73]:
pays_80=pays_80.drop(columns=["Country_y"])
pays_80 = pays_80.rename(columns={"Country_x": "Country"})

In [74]:
pays_80.to_csv("../data_clean/df_ACP.csv", index=False, encoding="utf-8")